export const headsets = [
  {
    id: 1,
    title: "JBL Quantum 100",
    url: "https://in.jbl.com/on/demandware.static/-/Library-Sites-SharedLibrary-JB/default/dwb2021379/glp/quantum-emea-pdp/images/lineup-quantum-300-visual.webp",
    originalPrice: 3999,
    salePrice: 2399,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Sony WHXB700",
    url: "https://www.sony.co.in/image/1cc1c23c2224adedbaaa8c3e656bef23?fmt=pjpeg&wid=165&bgcolor=FFFFFF&bgc=FFFFFF",
    originalPrice: 8990,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Sony WHCH520",
    url: "https://m.media-amazon.com/images/I/41lArSiD5hL._SX522_.jpg",
    originalPrice: 5990,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "JBL Tune 760 NC",
    url: "https://m.media-amazon.com/images/I/61QZnJ+vJyL._AC_UY218_.jpg",
    originalPrice: 7999,
    salePrice: 5499,
    rating: 4.5,
  },
  {
    id: 5,
    title: "Boat Rockerz 450",
    url: "https://m.media-amazon.com/images/I/51xxA+6E+xL._AC_UY218_.jpg",
    originalPrice: 3999,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "JBL Live 500 BT",
    url: "https://m.media-amazon.com/images/I/71tGxVL6axL._SX522_.jpg",
    originalPrice: 9999,
    salePrice: 3999,
    rating: 5,
  },
  {
    id: 7,
    title: "JBL Tune 720 BT",
    url: "https://m.media-amazon.com/images/I/51JNhjr4McL.jpg",
    originalPrice: 6499,
    salePrice: 5499,
    rating: 4,
  },
  {
    id: 8,
    title: "Noise Two Wireless",
    url: "https://m.media-amazon.com/images/I/512sO2L0k6L.jpg",
    originalPrice: 4999,
    salePrice: 2099,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Boat Rockerz 551 ANC",
    url: "https://m.media-amazon.com/images/I/61+VJT8U-LL._AC_UY218_.jpg",
    originalPrice: 7990,
    salePrice: 2999,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Boat Immortal IM 200",
    url: "https://m.media-amazon.com/images/I/61yggJpMNTL._AC_UY218_.jpg",
    originalPrice: 4990,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "HyperX Cloud Stinger 2",
    url: "https://m.media-amazon.com/images/I/61ll3eZ9XvL._AC_UY218_.jpg",
    originalPrice: 6097,
    salePrice: 4690,
    rating: 5,
  },
  {
    id: 12,
    title: "HyperX Cloud III",
    url: "https://m.media-amazon.com/images/I/81dkzD4hxIL._AC_UY218_.jpg",
    originalPrice: 11037,
    salePrice: 8490,
    rating: 4.5,
  }
];